### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by lenerd** [ZenGo-X/class#49]
Hi,

I noticed that this repository does not contain a license (except the third-party pari code). Would you consider adding a license file stating under which conditions this code may be used?

(Since you depend on PARI which is published under the GNU GPL v2, I would assume that this library counts as derived work and, therefore, must also be published under the GPL. I am not a license expert though.)

**Comment by omershlo** [comment]
thanks, good catch. 
I added a GPLv3 license

**Comment by lenerd** [comment]
Thanks!
